---
- name: update os
  hosts:
    - all
  gather_facts: false
  roles:
    - {role: steam/timezone, tags: timezone }
    - {role: steam/repository, action: hosts, tags: repository }
    - {role: steam/docker, action: registry, tags: docker }
    - {role: steam/python, tags: python }
