###################
# steam options
###################
# cluster domain
cluster_domain: domain.tld


#################
# respostory url
#################
deploy_ip: '2.6.1.2'
deploy_host: 'fuel.{{cluster_domain}}'
certs_repo_host: '{{deploy_host}}'
apt_repo_host: '{{deploy_host}}'
yum_repo_host: '{{deploy_host}}'
pip_repo_host: '{{deploy_host}}'
certs_repo_url: 'http://{{certs_repo_host}}/repository/certs'
yum_repo_url: 'http://{{yum_repo_host}}/repository/yum'
apt_sources_url: 'http://{{apt_repo_host}}/repository'
pip_repo_url: 'http://{{pip_repo_host}}/repository/pypi/simple'


timezone: 'Asia/Shanghai'


docker_registry: "{{deploy_host}}"
docker_registry_username: "admin"
docker_registry_password: "admin123"


# Common options used throughout Docker
docker_common_options:
  auth_password: "{{ docker_registry_password }}"
  auth_registry: "{{ docker_registry }}"
  auth_username: "{{ docker_registry_username }}"
  environment:
    KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
  restart_policy: "{{ docker_restart_policy }}"
  restart_retries: "{{ docker_restart_policy_retry }}"

python_pkg_install: [ansible, docker]
